INSERT INTO quiz (title, description, level, number_question)
VALUES ('Quiz JS', 'Quiz sur le langage JavaScript', 'Débutant', 3),
        ('Quiz JS sur les types de données', 'Quiz sur les types de données en JavaScript', 'Débutant', 5),
        ('Quiz JS sur les boucles', 'Quiz sur les types de boucle et leurs usages en JS', 'Avancé', 5),
        ('Quiz JS sur les objets', 'Quiz sur les objets en JS', 'Avancé', 5),
        ('Quiz JS sur les tableaux', 'Quiz sur les tableaux en JS', 'Avancé', 5),
        ('Quiz JS sur la POO', 'La programmation orientée objet en JS', 'Difficile', 10);

INSERT INTO question (description, doc_link, quiz_id)
VALUES -- question sur le quiz générale sur les bases de js
        ('Quelle est la syntaxe pour créer un tableau en JS ?', 'https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Array', 1),
        ('Quelle est la syntaxe pour créer un objet en JS ?', 'https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Object', 1),
        ('Quelle est la syntaxe pour créer une fonction en JS ?', 'https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Function', 1),
        -- question sur les types de données
        ('Quel est le type de données de la valeur 42 ?', 'https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Number', 2),
        ('Quel est le type de données de la valeur "42" ?', 'https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/String', 2),
        ('Quel est le type de données de la valeur true ?', 'https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Boolean', 2),
        ('Quel est le type de données de la valeur null ?', 'https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/null', 2),
        ('Quel est le type de données de la valeur undefined ?', 'https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/undefined', 2),
        -- question sur les boucles
        ('Quelle est la syntaxe pour créer une boucle for en JS ?', 'https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Instructions/for', 3),
        ('Quelle est la syntaxe pour créer une boucle while en JS ?', 'https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Instructions/while', 3),
        ('Quelle est la syntaxe pour créer une boucle do while en JS ?', 'https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Instructions/do...while', 3),
        ('Quelle est la syntaxe pour créer une boucle for of en JS ?', 'https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Instructions/for...of', 3),
        ('Quelle est la syntaxe pour créer une boucle for in en JS ?', 'https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Instructions/for...in', 3),
        -- question sur les objets
        ('Quelle est la syntaxe pour créer un objet en JS ?', 'https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Object', 4),
        ('Quelle est la syntaxe pour créer une méthode dans un objet en JS ?', 'https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Object', 4),
        ('Quelle est la syntaxe pour créer une propriété dans un objet en JS ?', 'https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Object', 4),
        ('Quelle est la syntaxe pour créer un constructeur en JS ?', 'https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Object', 4),
        ('Quelle est la syntaxe pour créer une classe en JS ?', 'https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Object', 4),
        -- question sur les tableaux
        ('Quelle est la syntaxe pour créer un tableau en JS ?', 'https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Array', 5),
        ('Quelle est la syntaxe pour ajouter un élément dans un tableau en JS ?', 'https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Array', 5),
        ('Quelle est la syntaxe pour supprimer un élément dans un tableau en JS ?', 'https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Array', 5),
        ('Quelle est la syntaxe pour supprimer le dernier élément dans un tableau en JS ?', 'https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Array', 5),
        ('Quelle est la syntaxe pour supprimer le premier élément dans un tableau en JS ?', 'https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Array', 5),
        -- question sur la POO
        ('Quelle est la syntaxe pour créer une classe en JS ?', 'https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Object', 6),
        ('Quelle est la syntaxe pour créer une méthode dans une classe en JS ?', 'https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Object', 6),
        ('Quelle est la syntaxe pour créer une propriété dans une classe en JS ?', 'https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Object', 6),
        ('Quelle est la syntaxe pour créer un constructeur dans une classe en JS ?', 'https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Object', 6),
        ('Quelle est la syntaxe pour créer une classe enfant en JS ?', 'https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Object', 6),
        ('Quelle est la syntaxe pour créer une méthode dans une classe enfant en JS ?', 'https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Object', 6),
        ('Quelle est la syntaxe pour créer une propriété dans une classe enfant en JS ?', 'https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Object', 6),
        ('Quelle est la syntaxe pour créer un constructeur dans une classe enfant en JS ?', 'https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Object', 6),
        ('Quelle est la syntaxe pour créer une classe enfant en JS ?', 'https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Object', 6),
        ('Quelle est la syntaxe pour créer une méthode dans une classe enfant en JS ?', 'https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Object', 6);
        
INSERT INTO proposition (description, is_true, question_id)
VALUES 
('var tableau = new Array();', TRUE, 1),
('var tableau = create Array();', FALSE, 1),
('var tableau = Array[];', FALSE, 1),
('var tableau = newArray[];', FALSE, 1),
('var objet = new Object();', FALSE, 2),
('var objet = {};', TRUE, 2),
('var objet = Object.new();', FALSE, 2),
('var objet = createObject();', FALSE, 2),
('function maFonction() {}', TRUE, 3),
('var maFonction = function[];', FALSE, 3),
('var maFonction = Function();', FALSE, 3),
('function: maFonction() {}', FALSE, 3),
('Number', TRUE, 4),
('String', FALSE, 4),
('Boolean', FALSE, 4),
('Object', FALSE, 4),
('Number', FALSE, 5),
('String', TRUE, 5),
('Boolean', FALSE, 5),
('Object', FALSE, 5),
('Number', FALSE, 6),
('String', TRUE, 6),
('Boolean', FALSE, 6),
('Object', FALSE, 6),
('Number', FALSE, 7),
('String', FALSE, 7),
('Boolean', TRUE, 7),
('Object', FALSE, 7),
('Number', FALSE, 8),
('String', FALSE, 8),
('Boolean', FALSE, 8),
('Object', TRUE, 8),
('Number', FALSE, 9),
('String', FALSE, 9),
('Boolean', FALSE, 9),
('Undefined', TRUE, 9),
('for (var i = 0; i < 10; i++) {}', TRUE, 10),
('for var i = 0; i < 10; i++ {}', FALSE, 10),
('for (var i; i < 10; i++) {}', FALSE, 10),
('for (var i = 0; i++) {}', FALSE, 10),
('while (condition) {}', TRUE, 11),
('while condition {}', FALSE, 11),
('while () {}', FALSE, 11),
('do {} while (condition);', FALSE, 11),
('do {} while (condition);', TRUE, 12),
('do while (condition) {}', FALSE, 12),
('while (condition) {}', FALSE, 12),
('for (condition) {}', FALSE, 12),
('for (var item of collection) {}', TRUE, 13),
('for var item of collection {}', FALSE, 13),
('for (var item in collection) {}', FALSE, 13),
('while (var item of collection) {}', FALSE, 13),
('for (var item in collection) {}', TRUE, 14),
('for var item in collection {}', FALSE, 14),
('for (var item of collection) {}', FALSE, 14),
('while (var item in collection) {}', FALSE, 14),
('var objet = new Object();', TRUE, 15),
('var objet = Object();', FALSE, 15),
('var objet = {};', TRUE, 15),
('var objet = createObject();', FALSE, 15),
('objet.method = function() {};', TRUE, 16),
('function method() {} dans objet', FALSE, 16),
('objet = {method() {}};', TRUE, 16),
('method: function() {} dans objet', FALSE, 16),
('objet.property = "value";', TRUE, 17),
('var property = "value" dans objet', FALSE, 17),
('objet = {property: "value"};', TRUE, 17),
('property: "value" dans objet', FALSE, 17),
('function Object() {}', TRUE, 18),
('objet.constructor = function() {};', FALSE, 18),
('var constructor = function() {} dans objet', FALSE, 18),
('constructor: function() {} dans objet', FALSE, 18),
('class MyClass {}', TRUE, 19),
('function MyClass() {}', FALSE, 19),
('var MyClass = class {};', TRUE, 19),
('var MyClass = new Class();', FALSE, 19),
('var tableau = new Array();', TRUE, 20),
('var tableau = Array();', TRUE, 20),
('var tableau = [];', TRUE, 20),
('var tableau = createArray();', FALSE, 20),
('tableau.push("element");', TRUE, 21),
('tableau.add("element");', FALSE, 21),
('tableau.insert("element");', FALSE, 21),
('push("element") dans tableau;', FALSE, 21),
('tableau.remove("element");', FALSE, 22),
('delete tableau[0];', FALSE, 22),
('tableau.splice(index, 1);', TRUE, 22),
('remove("element") de tableau;', FALSE, 22),
('tableau.pop();', TRUE, 23),
('tableau.deleteLast();', FALSE, 23),
('delete tableau[tableau.length - 1];', FALSE, 23),
('pop() de tableau;', TRUE, 23),
('tableau.shift();', TRUE, 24),
('tableau.deleteFirst();', FALSE, 24),
('delete tableau[0];', TRUE, 24),
('shift() de tableau;', TRUE, 24),
('class MyClass {}', TRUE, 25),
('function MyClass() {}', FALSE, 25),
('var MyClass = class {};', TRUE, 25),
('var MyClass = new Class();', FALSE, 25),
('class MyClass { myMethod() {} }', TRUE, 26),
('function MyClass() { this.myMethod = function() {} }', FALSE, 26),
('var MyClass = class { myMethod() {} }', TRUE, 26),
('var MyClass = { myMethod: function() {} }', FALSE, 26),
('class MyClass { constructor() {} }', TRUE, 27),
('function MyClass() { this.constructor = function() {} }', FALSE, 27),
('var MyClass = class { constructor() {} }', TRUE, 27),
('var MyClass = { constructor: function() {} }', FALSE, 27),
('class ChildClass extends ParentClass {}', TRUE, 28),
('function ChildClass() {} inherits ParentClass', FALSE, 28),
('var ChildClass = class extends ParentClass {}', TRUE, 28),
('var ChildClass = new Extends(ParentClass);', FALSE, 28),
('class ChildClass extends ParentClass { myMethod() {} }', TRUE, 29),
('function ChildClass() { ParentClass.call(this); this.myMethod = function() {} }', FALSE, 29),
('var ChildClass = class extends ParentClass { myMethod() {} }', TRUE, 29),
('var ChildClass = { extends ParentClass, myMethod: function() {} }', FALSE, 29);
